### ISSUE TITLE
Edge Bleeding

### ISSUE THREAD

**Issue by nobananasforyou** [dubhater/vapoursynth-smoothuv#2]
Hey,

I compared avs' SmoothUV2 port to yours and the big benefit is that the color accuracy is maintained, however, the plugin is causing edge bleeding. The colors are being pulled out of the edges to the left side along with a green stripe on the right. Here's an image comparison: https://slow.pics/c/3uhtEA1m

Script:
import vapoursynth as vs
core = vs.core

src = core.d2v.Source(r'sti_01.d2v', rff=False)
src = core.smoothuv.SmoothUV(src, radius=1, threshold=225)
src.set_output()

Kind Regards

**Comment by dubhater** [comment]
Does this work better? [test.zip](https://github.com/dubhater/vapoursynth-smoothuv/files/8814571/test.zip)

**Comment by nobananasforyou** [comment]
Yup. It works but there is some color discoloration. Green leaves' veins and stems become slightly white. I've made an image comparison for illustration: https://slow.pics/c/q7bsMbD5

**Comment by dubhater** [comment]
I think that's normal.
